2024-06-18 07:27:57,016 ERROR app Thread-19 (process_request_thread) : Exception on /query [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 105, in query_add_page
    user_id = User.get_id(),
             ^^^^^^^^^^^^^
TypeError: User.get_id() missing 1 required positional argument: 'self'
2024-06-18 07:29:21,173 ERROR app Thread-22 (process_request_thread) : Exception on /query [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 105, in query_add_page
    user_id = User.get_id(),
             ^^^^^^^^^^^^^
TypeError: User.get_id() missing 1 required positional argument: 'self'
2024-06-18 07:32:15,142 INFO app MainThread : MoodyWorld startup [in /home/myname/Workspace/Moody-World/app/__init__.py:44]
2024-06-18 07:32:31,543 ERROR app Thread-7 (process_request_thread) : Exception on /query [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 105, in query_add_page
    user_id = User.get_id(),
             ^^^^^^^^^^^^^
TypeError: User.get_id() missing 1 required positional argument: 'self'
2024-06-18 07:33:09,992 INFO app MainThread : MoodyWorld startup [in /home/myname/Workspace/Moody-World/app/__init__.py:44]
2024-06-18 07:33:31,683 ERROR app Thread-7 (process_request_thread) : Exception on /query [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 105, in query_add_page
    user_id = User.get_id(),
             ^^^^^^^^^^^^^
TypeError: User.get_id() missing 1 required positional argument: 'self'
2024-06-18 07:34:50,572 INFO app MainThread : MoodyWorld startup [in /home/myname/Workspace/Moody-World/app/__init__.py:44]
2024-06-18 07:35:00,234 ERROR app Thread-7 (process_request_thread) : Exception on /query [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 105, in query_add_page
    user_id = User.get_id(self),
                         ^^^^
NameError: name 'self' is not defined
2024-06-18 08:01:32,753 INFO app MainThread : MoodyWorld startup [in /home/myname/Workspace/Moody-World/app/__init__.py:44]
